FROM mcr.microsoft.com/playwright:v1.40.0-jammy

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npx prisma generate
RUN npx playwright install chromium

COPY . .

CMD node src/workers/scrapeWorker.js
